/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rodrigogelmi (https://sketchfab.com/rodrigogelmi)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/charging-bull-3c0ad02af35d490b8c4163b3bbab905e
title: Charging Bull
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/bull/bull.glb')
  useFrame(() => (group.current.rotation.y -= 0.01))

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 2, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes['0'].geometry} material={materials.material} castShadow />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bull/bull.glb')
